### ISSUE TITLE
Sarocladium oryzae (PDO:0000083)

### ISSUE THREAD

**Issue by seymourmegan** [Planteome/plant-disease-ontology#146]
Sarocladium oryzae (PDO:0000083)
def'n: A fungal species (PDO:0000069) that causes various plant fungal diseases (PDO:0000004).

Name Source: [Rice Diseases APS](http://www.apsnet.org/publications/commonnames/Pages/Rice.aspx)
NCBI_Taxonomy_ID: 284135
EOL: 1013725
Alternative Names:
- Acrocylindrium oryzae Sawada (APS)
- Sarocladium oryzae (Sawada) W. Gams & D. Hawksworth (APS) - Authority

**Comment by seymourmegan** [comment]
Sarocladium oryzae (PDO:0000083)

Updated and added relationships between diseases and pathogens.
- Changed relation: from Sarocladium oryzae (PDO:0000083) causal_agent_in Sarocladium oryzae pecky rice fungal disease (PDO:0000082) ---> Sarocladium oryzae pecky rice fungal disease (PDO:0000082) has_causal-agent Sarocladium oryzae (PDO:0000083).
- Added relation: rice sheath rot fungal disease (PDO:0000053) has_causal-agent Sarocladium oryzae (PDO:0000083).

Updated Sarocladium oryzae (PDO:0000083) def'n.
- Old def'n: A fungal species (PDO:0000069) that causes various plant fungal diseases (PDO:0000004).
- New def'n: A fungal species (PDO:0000069) that causes Sarocladium oryzae pecky rice fungal disease (PDO:0000082) and rice sheath rot fungal disease (PDO:0000053).

**Comment by phismith** [comment]
These are not definitions. They are statements about instances of the
species in question (that some of them cause that disease). For species the
correct definitional approach is just to identify the relevant NCBI taxon.
BS

**Comment by cmungall** [comment]
@phismith is correct - I believe the eventual plan is to replace the taxon subset of PDO with NCBITaxon?

**Comment by cooperl09** [comment]
Yes, in progress
