### ISSUE TITLE
rice brown spot fungal disease (PDO:0000033)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-disease-ontology#24]
Moved rice brown spot fungal disease ([PDO:0000033](http://purl.obolibrary.org/obo/PDO_0000033)) to be a child of rice fungal disease ([PDO:0000081](http://purl.obolibrary.org/obo/PDO_0000081)) 

Proposed definition: A rice fungal disease ([PDO:0000081](http://purl.obolibrary.org/obo/PDO_0000081)) caused by Cochliobolus miyabeanus ([PDO:0000034](http://purl.obolibrary.org/obo/PDO_0000034)).

Reported by: saiuppala

Original Ticket: [obo/plant-stress-ontology-pso-tracker/25](https://sourceforge.net/p/obo/plant-stress-ontology-pso-tracker/25)

**Comment by planteome-user** [comment]
- **summary**: rice brown spot (PDO:0000033) --> rice brown spot fungal disease (PDO:0000033)
- Description has changed:
  
  Proposed definition: A rice fungal disease (PDO:0000081) caused by Cochliobolus miyabeanus (PDO:0000034).

Original comment by: saiuppala

**Comment by cooperl09** [comment]
Changed relation: 
from: Bipolaris oryzae (PDO:0000034) causal_agent_in rice brown spot fungal disease (PDO:0000033) 
To:  rice brown spot fungal disease (PDO:0000033) has_causal-agent Bipolaris oryzae (PDO:0000034)
