### ISSUE TITLE
rice narrow brown leaf spot fungal disease (PDO:0000049)

### ISSUE THREAD

**Issue by planteome-user** [Planteome/plant-disease-ontology#3]
Revised the definition of rice narrow brown leaf spot fungal disease ([PDO:0000049](http://purl.obolibrary.org/obo/PDO_0000049)) and moved it to be a child of rice fungal disease ([PDO:0000081](http://purl.obolibrary.org/obo/PDO_0000081))

Proposed def'n: A rice fungal disease ([PDO:0000081](http://purl.obolibrary.org/obo/PDO_0000081)) caused by Cercospora janseana ([PDO:0000050](http://purl.obolibrary.org/obo/PDO_0000050)).

Reported by: saiuppala

Original Ticket: [obo/plant-stress-ontology-pso-tracker/3](https://sourceforge.net/p/obo/plant-stress-ontology-pso-tracker/3)

**Comment by planteome-user** [comment]
- **summary**: New term: rice narrow brown leaf spot (PDO:0000049) --> rice narrow brown leaf spot (PDO:0000049)
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1,5 +1,3 @@
-
-
-Created a new term: rice narrow brown leaf spot (PDO:0000049) to be a child of rice fungal disease (PDO:0000081)
+Revised the definition of rice narrow brown leaf spot (PDO:0000049) a child of rice fungal disease (PDO:0000081)

 Proposed def'n: A rice fungal disease (PDO:0000081) caused by Cercospora janseana (PDO:0000050).

```

Original comment by: saiuppala

**Comment by planteome-user** [comment]
- **status**: open --> pending
- **assigned_to**: Sai Sree Uppala

Original comment by: saiuppala

**Comment by planteome-user** [comment]
- **labels**:  --> revision
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1,3 +1,3 @@
-Revised the definition of rice narrow brown leaf spot (PDO:0000049) a child of rice fungal disease (PDO:0000081)
+Revised the definition of rice narrow brown leaf spot (PDO:0000049) and moved it to be a child of rice fungal disease (PDO:0000081)

 Proposed def'n: A rice fungal disease (PDO:0000081) caused by Cercospora janseana (PDO:0000050).

```

Original comment by: saiuppala

**Comment by planteome-user** [comment]
- **summary**: rice narrow brown leaf spot (PDO:0000049) --> rice narrow brown leaf spot fungal disease (PDO:0000049)
- Description has changed:

Diff:

```

--- old
+++ new
@@ -1,3 +1,3 @@
-Revised the definition of rice narrow brown leaf spot (PDO:0000049) and moved it to be a child of rice fungal disease (PDO:0000081)
+Revised the definition of rice narrow brown leaf spot fungal disease (PDO:0000049) and moved it to be a child of rice fungal disease (PDO:0000081)

 Proposed def'n: A rice fungal disease (PDO:0000081) caused by Cercospora janseana (PDO:0000050).

```

Original comment by: saiuppala

**Comment by planteome-user** [comment]
- **status**: pending --> closed
- **assigned_to**: Sai Sree Uppala --> Laurel Cooper
- **private**: No --> Yes

Original comment by: cooperl09

**Comment by seymourmegan** [comment]
rice narrow brown leaf spot fungal disease (PDO:0000049)
Updated def'n to match the name change of Cercospora janseana (PDO:0000050) to Passalora janseana.
- Old def'n: A rice fungal disease (PDO:0000081) caused by Cercospora janseana (PDO:0000050).
- New def'n: A rice fungal disease (PDO:0000081) caused by Passalora janseana (PDO:0000050).

**Comment by phismith** [comment]
This does not seem to make sense.
How can a disease be defined as a fungal species?
BS

**Comment by cooperl09** [comment]
It was just a typo in the commit- fixed now. :-)
